# Four Demos

In [1]:
# use pip (or, conda) to make sure numpy is installed:
!pip -q install numpy  

In [2]:
from mpyc.runtime import mpc
import secretsanta, id3gini, lpsolver, cnnmnist

## Default runs

In [3]:
mpc.run(secretsanta.main())

Setting input to default = 8
2019-10-13 22:37:36,051 Start MPyC runtime v0.5.10
Using secure integers: SecInt32
2 [1, 0]
3 [1, 2, 0]
4 [1, 3, 0, 2]
5 [4, 3, 1, 0, 2]
6 [3, 0, 4, 5, 2, 1]
7 [4, 6, 1, 5, 3, 0, 2]
8 [3, 2, 7, 4, 6, 0, 5, 1]
Using secure fixed-point numbers: SecFxp32:16
2 [1.0, 0.0]
3 [2.0, 0.0, 1.0]
4 [2.0, 3.0, 0.0, 1.0]
5 [1.0, 3.0, 0.0, 4.0, 2.0]
6 [5.0, 2.0, 3.0, 0.0, 1.0, 4.0]
7 [2.0, 3.0, 5.0, 6.0, 1.0, 0.0, 4.0]
8 [4.0, 6.0, 5.0, 1.0, 2.0, 0.0, 7.0, 3.0]
Using secure prime fields: SecFld3(GF(11))
2 [1, 0]
3 [2, 0, 1]
4 [3, 2, 1, 0]
5 [3, 4, 0, 1, 2]
6 [1, 2, 5, 4, 0, 3]
7 [5, 2, 4, 6, 3, 1, 0]
8 [7, 2, 4, 5, 1, 0, 3, 6]
Using secure binary fields: SecFld3(GF(2^3))
2 [1, 0]
3 [1, x, 0]
4 [x, x+1, 1, 0]
5 [x^2, x, 1, 0, x+1]
6 [x+1, 0, x^2, x, x^2+1, 1]
7 [x^2+1, x+1, x^2+x, 1, x, x^2, 0]
8 [1, x+1, x^2, x^2+x+1, x^2+x, x, 0, x^2+1]
Using secure quinary fields: SecFld4(GF(5^2))
2 [1, 0]
3 [2, 0, 1]
4 [3, 2, 1, 0]
5 [1, 2, 4, 0, 3]
6 [4, x, 0, 1, 3, 2]
7 [x, x+1, 0, 4

In [4]:
mpc.run(id3gini.main())

Using secure integers: SecInt32
dataset: tennis with 14 samples and 4 attributes
2019-10-13 22:37:39,550 Start MPyC runtime v0.5.10
2019-10-13 22:37:39,566 Attribute node 0
2019-10-13 22:37:39,566 Leaf node label 1
2019-10-13 22:37:39,585 Attribute node 3
2019-10-13 22:37:39,589 Leaf node label 0
2019-10-13 22:37:39,593 Leaf node label 1
2019-10-13 22:37:39,601 Attribute node 2
2019-10-13 22:37:39,605 Leaf node label 0
2019-10-13 22:37:39,609 Leaf node label 1
2019-10-13 22:37:39,609 Stop MPyC runtime -- elapsed time: 0:00:00.058882
Decision tree of depth 2 and size 8: 
if Outlook == Overcast: Yes
if Outlook == Rain: 
|   if Wind == Strong: No
|   if Wind == Weak: Yes
if Outlook == Sunny: 
|   if Humidity == High: No
|   if Humidity == Normal: Yes


In [5]:
mpc.run(lpsolver.main())

2019-10-13 22:37:41,797 Setting certificate file to default = c0.cert
2019-10-13 22:37:41,797 Start MPyC runtime v0.5.10
2019-10-13 22:37:41,797 0 Termination?...
2019-10-13 22:37:41,797 1 Determining pivot...
2019-10-13 22:37:41,797 1 Updating tableau...
2019-10-13 22:37:41,797 1 Termination?...
2019-10-13 22:37:41,797 2 Determining pivot...
2019-10-13 22:37:41,813 2 Updating tableau...
2019-10-13 22:37:41,813 2 Termination?...
2019-10-13 22:37:41,813 Termination...
 max(f) = 21 / 2 = 10.500000
2019-10-13 22:37:41,813 Computing solution...
2019-10-13 22:37:41,813 Computing dual solution...
2019-10-13 22:37:41,823 Stop MPyC runtime -- elapsed time: 0:00:00.025458
2019-10-13 22:37:41,823 Writing output to c0.cert.


In [6]:
mpc.run(cnnmnist.main()) # takes a minute or so

2019-10-13 22:37:43,804 Start MPyC runtime v0.5.10
2019-10-13 22:37:43,820 --------------- INPUT   -------------
Type = SecInt37, range = (8560, 8561)
Labels: [2]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0

## Runs with specific inputs

In [7]:
import sys
mpc.logging(False)

sys.argv[1:] = ['6']
mpc.run(secretsanta.main())

print()

sys.argv[1:] = ['-i', '2']
mpc.run(id3gini.main())

print()

sys.argv[1:] = ['-d', 'LPExample_R20']
mpc.options.bit_length = 84
mpc.run(lpsolver.main())

print()

sys.argv[1:] = ['1.5']  # forces use of secure fixed-point arithmetic
mpc.run(cnnmnist.main())     # takes a minute or so

sys.argv[1:] = []

Using secure integers: SecInt32
2 [1, 0]
3 [1, 2, 0]
4 [1, 3, 0, 2]
5 [4, 0, 1, 2, 3]
6 [2, 5, 3, 0, 1, 4]
Using secure fixed-point numbers: SecFxp32:16
2 [1.0, 0.0]
3 [1.0, 2.0, 0.0]
4 [3.0, 2.0, 1.0, 0.0]
5 [3.0, 4.0, 0.0, 1.0, 2.0]
6 [2.0, 5.0, 1.0, 4.0, 0.0, 3.0]
Using secure prime fields: SecFld2(GF(7))
2 [1, 0]
3 [1, 2, 0]
4 [1, 2, 3, 0]
5 [3, 4, 1, 2, 0]
6 [3, 2, 5, 0, 1, 4]
Using secure binary fields: SecFld3(GF(2^3))
2 [1, 0]
3 [1, x, 0]
4 [x, x+1, 0, 1]
5 [1, x+1, 0, x^2, x]
6 [x^2+1, 0, 1, x^2, x, x+1]
Using secure quinary fields: SecFld4(GF(5^2))
2 [1, 0]
3 [1, 2, 0]
4 [3, 2, 0, 1]
5 [1, 3, 0, 4, 2]
6 [x, 0, 1, 4, 3, 2]
Using secure extension fields (medium prime): SecFld24(GF(11^7))
2 [1, 0]
3 [2, 0, 1]
4 [1, 3, 0, 2]
5 [3, 2, 4, 1, 0]
6 [5, 0, 1, 4, 3, 2]
Using secure extension fields (larger prime): SecFld30(GF(1031^3))
2 [1, 0]
3 [2, 0, 1]
4 [1, 3, 0, 2]
5 [2, 3, 1, 4, 0]
6 [1, 3, 5, 0, 2, 4]

Using secure integers: SecInt95
dataset: car with 1728 samples and 6 attribut