# Four Demos

In [1]:
# use pip (or, conda) to make sure numpy is installed:
!pip -q install numpy  

In [2]:
from mpyc.runtime import mpc
import secretsanta, id3gini, lpsolver, cnnmnist

## Default runs

In [3]:
mpc.run(secretsanta.main())

Setting input to default = 8
2020-06-16 11:44:36,303 Start MPyC runtime v0.6.6
Using secure integers: SecInt32
2 [1, 0]
3 [2, 0, 1]
4 [1, 0, 3, 2]
5 [3, 0, 4, 1, 2]
6 [2, 4, 3, 1, 5, 0]
7 [2, 6, 3, 4, 5, 0, 1]
8 [5, 3, 0, 7, 2, 6, 4, 1]
Using secure fixed-point numbers: SecFxp32:16
2 [1.0, 0.0]
3 [2.0, 0.0, 1.0]
4 [1.0, 3.0, 0.0, 2.0]
5 [3.0, 4.0, 0.0, 2.0, 1.0]
6 [2.0, 4.0, 3.0, 5.0, 1.0, 0.0]
7 [2.0, 5.0, 3.0, 1.0, 6.0, 4.0, 0.0]
8 [1.0, 7.0, 0.0, 5.0, 3.0, 6.0, 2.0, 4.0]
Using secure prime fields: SecFld3(GF(11))
2 [1, 0]
3 [2, 0, 1]
4 [1, 0, 3, 2]
5 [3, 2, 0, 4, 1]
6 [4, 2, 1, 5, 0, 3]
7 [5, 6, 3, 4, 1, 0, 2]
8 [4, 2, 1, 6, 5, 7, 3, 0]
Using secure binary fields: SecFld3(GF(2^3))
2 [1, 0]
3 [x, 0, 1]
4 [x, 0, x+1, 1]
5 [x, x+1, x^2, 0, 1]
6 [x, 0, x^2+1, 1, x+1, x^2]
7 [x, 0, x^2+x, x^2+1, 1, x^2, x+1]
8 [x+1, x^2, x^2+x+1, x^2+1, x, x^2+x, 1, 0]
Using secure quinary fields: SecFld4(GF(5^2))
2 [1, 0]
3 [2, 0, 1]
4 [2, 3, 0, 1]
5 [4, 0, 3, 1, 2]
6 [2, 0, x, 4, 1, 3]
7 [1, 2, 3, x+1,

In [4]:
mpc.run(id3gini.main())

Using secure integers: SecInt32
dataset: tennis with 14 samples and 4 attributes
2020-06-16 11:44:37,625 Start MPyC runtime v0.6.6
2020-06-16 11:44:37,641 Attribute node 0
2020-06-16 11:44:37,641 Leaf node label 1
2020-06-16 11:44:37,641 Attribute node 3
2020-06-16 11:44:37,657 Leaf node label 0
2020-06-16 11:44:37,657 Leaf node label 1
2020-06-16 11:44:37,671 Attribute node 2
2020-06-16 11:44:37,675 Leaf node label 0
2020-06-16 11:44:37,675 Leaf node label 1
2020-06-16 11:44:37,679 Stop MPyC runtime -- elapsed time: 0:00:00.054079
Decision tree of depth 2 and size 8: 
if Outlook == Overcast: Yes
if Outlook == Rain: 
|   if Wind == Strong: No
|   if Wind == Weak: Yes
if Outlook == Sunny: 
|   if Humidity == High: No
|   if Humidity == Normal: Yes


In [5]:
mpc.run(lpsolver.main())

Using secure 8-bit integers: SecInt8
dataset: uvlp with 2 constraints and 3 variables (scale factor 1)
2020-06-16 11:44:39,096 Start MPyC runtime v0.6.6
2020-06-16 11:44:39,096 Iteration 1/2: 0.0 pivot=1.0
2020-06-16 11:44:39,096 Iteration 2/2: 10.0 pivot=3.0
max = 37 / 3 / 1 = 12.333333333333334 in 2 iterations
2020-06-16 11:44:39,111 Solution x
2020-06-16 11:44:39,111 Dual solution y
verification c.x == y.b, A.x <= b, x >= 0, y.A <= c, y <= 0: True
solution = [1.3333333333333333, 0.3333333333333333, 0.0]
2020-06-16 11:44:39,111 Stop MPyC runtime -- elapsed time: 0:00:00.015610


In [6]:
mpc.run(cnnmnist.main()) # takes a minute or so

2020-06-16 11:44:40,273 Start MPyC runtime v0.6.6
2020-06-16 11:44:40,273 --------------- INPUT   -------------
Type = SecInt37, range = (6208, 6209)
Labels: [7]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 

## Runs with specific inputs

In [7]:
import sys
mpc.logging(False)

sys.argv[1:] = ['6']
mpc.run(secretsanta.main())

print()

sys.argv[1:] = ['-i', '2']
mpc.run(id3gini.main())

print()

sys.argv[1:] = ['-i', '1']
mpc.run(lpsolver.main())

print()

sys.argv[1:] = ['1.5']  # forces use of secure fixed-point arithmetic
mpc.run(cnnmnist.main())     # takes a minute or so

sys.argv[1:] = []

Using secure integers: SecInt32
2 [1, 0]
3 [1, 2, 0]
4 [1, 3, 0, 2]
5 [3, 4, 1, 2, 0]
6 [3, 4, 0, 1, 5, 2]
Using secure fixed-point numbers: SecFxp32:16
2 [1.0, 0.0]
3 [2.0, 0.0, 1.0]
4 [3.0, 2.0, 0.0, 1.0]
5 [2.0, 3.0, 4.0, 0.0, 1.0]
6 [3.0, 2.0, 5.0, 0.0, 1.0, 4.0]
Using secure prime fields: SecFld2(GF(7))
2 [1, 0]
3 [1, 2, 0]
4 [1, 2, 3, 0]
5 [1, 3, 4, 2, 0]
6 [3, 4, 1, 0, 5, 2]
Using secure binary fields: SecFld3(GF(2^3))
2 [1, 0]
3 [x, 0, 1]
4 [1, 0, x+1, x]
5 [x+1, x, x^2, 0, 1]
6 [x^2, x, x+1, 0, x^2+1, 1]
Using secure quinary fields: SecFld4(GF(5^2))
2 [1, 0]
3 [1, 2, 0]
4 [3, 2, 0, 1]
5 [2, 3, 4, 1, 0]
6 [3, 4, 0, x, 1, 2]
Using secure extension fields (medium prime): SecFld24(GF(11^7))
2 [1, 0]
3 [1, 2, 0]
4 [2, 3, 1, 0]
5 [2, 0, 3, 4, 1]
6 [1, 3, 5, 4, 0, 2]
Using secure extension fields (larger prime): SecFld30(GF(1031^3))
2 [1, 0]
3 [1, 2, 0]
4 [1, 0, 3, 2]
5 [2, 4, 3, 0, 1]
6 [2, 0, 5, 1, 3, 4]

Using secure integers: SecInt95
dataset: car with 1728 samples and 6 attribut